version: '3'

services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
